Web/code execution
bounswe/bounswe2024group9 pull request #295
Opened 2024-11-20 21:35 UTC by FatihAkgoz

Changes in question detail pages are in this pr.

2024-11-21 00:12 UTC, Mutti499 commented on django_project_491/django_app/urls.py
> +    path('create_question/<int:user_id>/', question_views.create_question, name='create_question'),
User Id is taken in the header the URL can not be changed like that

2024-11-21 00:12 UTC, Mutti499 commented on django_project_491/django_app/urls.py
> +    path('run_code/<str:type>/<int:id>/', utilization_views.run_code_of_question_or_comment, name='run_code'),
Nice catch

2024-11-21 00:15 UTC, Mutti499 commented
This PR is changing a lot of code in backend and needs a lot of investigation in order to prevent overwrites. I will take one more look after [the PR](https://github.com/bounswe/bounswe2024group9/pull/286) is merged.

2024-11-21 15:07 UTC, serhan-cakmak commented
@Mutti499 I modified the endpoint as you requested!

2024-11-21 15:09 UTC, Mutti499 requested changes
Okey this is good and actually I can merge it but if you make the request I want it will be lot better.

2024-11-21 15:09 UTC, Mutti499 commented on koduyorum-web/src/PageComponents.js
> +        setUsername(storedUsername);
I really dont know if it is the right code or not since I didn't write front-end

2024-11-21 15:09 UTC, Mutti499 commented on django_project_491/django_app/views/question_views.py
> +        'likes': question.upvotes,
the field is not likes it is upvotes change that on frontend also

2024-11-21 19:35 UTC, Mutti499 commented
Yea the page seems good. Can you solve the merge conflicts so that I can merge the PR? @serhan-cakmak @FatihAkgoz

2024-11-21 20:11 UTC, serhan-cakmak commented
I reviewed the merge conflicts, but I found the one in feed.js too complicated since I didn't make any changes to that file. However, it shouldn't be an issue for you to resolve, @FatihAkgoz. If you need any help, just let me know.

2024-11-22 15:06 UTC, FatihAkgoz commented
I took a reverse merge and fixed the conflicts.

2024-11-22 15:06 UTC, merged